### ISSUE TITLE
Questbook doesn't work!

### ISSUE THREAD

**Issue by dragonriderworld** [Ronnie0982/Wynncraft-Reborn#1]
Hi,
i cant open the quests in the questbook...i can only track them..don't know why...

**Comment by Ronnie0982** [comment]
Hello,
I see... Have you other mods installed on the modpack.
And is there any errors when you try opening the questbook or are you testing the Beta of Wynncraft?

**Comment by Ronnie0982** [comment]
No information so case closed, open up if anything new
