### ISSUE TITLE
Cannot open quest on wiki

### ISSUE THREAD

**Issue by AlexejheroYTB** [Ronnie0982/Wynncraft-Reborn#2]
When right clicking a quest to open it in the wiki, `À_` is automatically added after the quest name, causing the wiki to say that the page was not found

**Comment by Ronnie0982** [comment]
I Will look into it soon :)

**Comment by Ronnie0982** [comment]
Can you name the Quest that does it?
I don't see the error on any of the quests that i tried?

**Comment by AlexejheroYTB** [comment]
All questis. For example if I rry to open `???`, it opens `???À_` on the wiki.

**Comment by Ronnie0982** [comment]
I see.
Well i can't get the problem on the updated version, so i will update the modpack so you can play with it
And you are not playing with any other 3rd party software that opens a webpage on your minecraft are you?

**Comment by AlexejheroYTB** [comment]
Nope, the webpage is opened directly in chrome

**Comment by Ronnie0982** [comment]
Okay, i will test some more then. Because i have not been able to recreate the problem yet, can you send a screenshot?

**Comment by AlexejheroYTB** [comment]
I will record a video of it.

**Comment by AlexejheroYTB** [comment]
A bit late, but here it is: https://www.youtube.com/watch?v=5Fs1wryn0y4

**Comment by Ronnie0982** [comment]
I see, i will take a look at it

**Comment by Ronnie0982** [comment]
Okay, i can't create the error, but maybe it's to do with Google Chrome, and when i use the Dev version of the modpack i can't recreate the problem.
I will send out a new version that hopefully should fix the issue.

**Comment by Ronnie0982** [comment]
Is the problem fixed for you?

**Comment by AlexejheroYTB** [comment]
Let me check.

**Comment by Ronnie0982** [comment]
I will close this issue because you haven't replied, if anything open an new ticket :)
