### ISSUE TITLE
Opening "The Tower of Amnesia" quest opens a disambiguation page

### ISSUE THREAD

**Issue by AlexejheroYTB** [Ronnie0982/Wynncraft-Reborn#3]
![image](https://user-images.githubusercontent.com/32238504/58695046-13fd9200-839d-11e9-8f4d-e4c23214a5ce.png)

Certain quests have a name that is exactly the same as a location on the map, so their wiki page must be suffixed with `(Quest)`

**Comment by Ronnie0982** [comment]
A Disambiguation page is a page that will display mulitple things with that name. As you see The Tower of Amnesia is a Location as well a Quest that you can complete.
