### ISSUE TITLE
GUI Scale

### ISSUE THREAD

**Issue by OfficialZygorg** [Ronnie0982/Wynncraft-Reborn#4]
Changing GUI scale on main menu or in game crashes the game, and cant reopen it

**Comment by Ronnie0982** [comment]
Is it when you try to make the GUI scale to AUTO?

**Comment by Ronnie0982** [comment]
And can you fix it by reinstalling the modpack?

**Comment by Ronnie0982** [comment]
I have sent the issue to the mod creator for the mod that is causes it, i hope to see a result soon

**Comment by Ronnie0982** [comment]
Okay, i can’t get any information from The mod creator, i got a way to fix it, so it should work in The next update

**Comment by Ronnie0982** [comment]
It should be fixed in the new update, if not you can open a new issue :)
