### ISSUE TITLE
Game has crashed, when world map has opened

### ISSUE THREAD

**Issue by Eltelikar** [Ronnie0982/Wynncraft-Reborn#5]
When I try to open the world map, the game crashes.
[crash-2019-06-19_21.12.51-client.txt](https://github.com/Ronnie0982/Wynncraft-Reborn/files/3307424/crash-2019-06-19_21.12.51-client.txt)

**Comment by Ronnie0982** [comment]
I have seen the changelog and tryed to recreate the problem, but it doesn't do it, have you done some settings on the map?

**Comment by Eltelikar** [comment]
No
It manifested itself this way: I broke questbook, no longer display quests. Restarting the game and resetting the settings didn't help
I reinstalled the mod and the client completely, and the quests began to appear normally, but there was a problem with the map.
Tried different settings, reset to default, but it did not help.

**Comment by Ronnie0982** [comment]
Hmm sounds strange... i will look at it

**Comment by Eltelikar** [comment]
Okay, thank you

**Comment by Eltelikar** [comment]
I added the WynnCraft client to the default launcher Minecraft, that is not through Twich, tried to run the game, it did not work
Then I ran the mod again through Twich and everything worked, the map works and quests too. The magic of some kind)

**Comment by Ronnie0982** [comment]
Okay? That Sounds more weird. Maybe it’s some map settings that doesn’t work with each other. Well thanks for the update

**Comment by Ronnie0982** [comment]
Well i must say that i can't receate the problem, so i'm not sure what was wrong, maybe some map settings, if you don't feel like a problem anymore then you can close the issue. If you believe that there is still some info or settings to help me find the error please leave them :)

**Comment by Ronnie0982** [comment]
Can you give me a update after the update?
