### ISSUE TITLE
Minimap Iconss & Compass Marker

### ISSUE THREAD

**Issue by DISHxRAIDS** [Ronnie0982/Wynncraft-Reborn#7]
**Describe the bug**
I am currently experiencing an issue with the minimap. Yesterday day this issue didn't happen but today the icons for all of the merchants, banks, ect. do not show up on the minimap (yes I have them all ticked as I can see them using "M". Also, the compass marker is no longer showing up on the minimap, but I have it ticked so it shows on the map when using "M". Also, when I update the position of the compass marker on the enlarged map, it does not show until I close and reopen the map. 

I have tried uninstalling and reinstalling the modpack as well as deleting the backups. Any help would be appreciated. Thanks.

**To Reproduce**
1. Not sure, worked fine yesterday but not today.

**Screenshots (if possible)**
![Compass Marker](https://user-images.githubusercontent.com/53453136/62088452-6a6b3d80-b233-11e9-805f-f5318697b665.png)
![Icons](https://user-images.githubusercontent.com/53453136/62088457-6d662e00-b233-11e9-8e1a-f66585757766.png)
![Enlarged Map](https://user-images.githubusercontent.com/53453136/62088461-6f2ff180-b233-11e9-97b1-dd84d3061389.png)
![Minimap](https://user-images.githubusercontent.com/53453136/62088465-70f9b500-b233-11e9-86be-abbdd8e9a5d7.png)

**Additional context**
Nah.
**Reborn Version**
Version: Most recent. 

**Modified Client**
Yes or No: No.

**Crashlog**
Set here as a spoiler or make a pastebin link:
Not a crash.

**Comment by Ronnie0982** [comment]
I see that is a problem, i will try to recreate the problem
Can you check what version of the book that you have
(Open the book and there so be a little banner with text displaying what version you have)
![Version](https://user-images.githubusercontent.com/4800840/62113048-2cfac480-b2b4-11e9-8ef4-47cd8e262591.PNG)

**Comment by Ronnie0982** [comment]
And check if this option is disabled
![Check](https://user-images.githubusercontent.com/4800840/62113243-84009980-b2b4-11e9-9af7-f8eb0760fbae.PNG)
In the map options of the book

**Comment by DISHxRAIDS** [comment]
I had to reintroduce the wynnlitis mod into the modpack and it fixed it, I'm all set now.Thanks!
    On Tuesday, July 30, 2019, 04:26:57 AM EDT, Ronnie0982 <notifications@github.com> wrote:  
 
 
And check if this option is disabled

In the map options of the book

**Comment by Ronnie0982** [comment]
Okay then, i will close the issue, if the error comes again please reopen the issue again :)
