### ISSUE TITLE
Tracked quest info

### ISSUE THREAD

**Issue by Therob5895games** [Ronnie0982/Wynncraft-Reborn#8]
The tracked quest info sits on top of the map and i can't find anyway to change the position of the map or tracked quest info.
![Capture](https://user-images.githubusercontent.com/7646902/70389860-4e3b9200-19c5-11ea-8b5e-7339d739f446.PNG)

**Comment by Ronnie0982** [comment]
Hmm sounds weird?
Have you changed some settings with the map?

**Comment by Therob5895games** [comment]
I've reset every setting in the book and it's the same. I do have a ultra wide monitor. Could it be compatibility issue?

![image](https://user-images.githubusercontent.com/7646902/70390358-93ae8e00-19ca-11ea-92ca-610f41b32e07.png)

**Comment by Ronnie0982** [comment]
It shouldn't be, but i'm not sure

**Comment by Ronnie0982** [comment]
It's it only the Time Valley mission?

**Comment by Therob5895games** [comment]
In the overlay settings I changed it to default and it looks like this.
![image](https://user-images.githubusercontent.com/7646902/70390420-1a636b00-19cb-11ea-8eb9-a10453d4d9bd.png)

**Comment by Ronnie0982** [comment]
Look at the minimap there is a little tiny red button that tells you where you need to go, but it's not big at all

**Comment by Ronnie0982** [comment]
![image](https://user-images.githubusercontent.com/4800840/70390458-78904e00-19cb-11ea-9c14-c48fc5e862b6.png)

**Comment by Therob5895games** [comment]
Yeah i can see that but when the text is in front of it it's hard too see. especially if you let the map turn with your position.

**Comment by Ronnie0982** [comment]
If you go into the Player Info Overlay and move the Quest Text section to another point on the screen i should work as you want :)

**Comment by Therob5895games** [comment]
I'll do that thanks for the help.

**Comment by Ronnie0982** [comment]
No problem
